services:

  proxy-c3:
    image: nginx:latest
    container_name: proxy-cliente3
    restart: unless-stopped
    volumes:
      - ./clientes/cliente3/proxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - isp_net
      - cliente3_net

  portal-c3:
    build:
      context: ./clientes/cliente3/portal
    container_name: portal-cliente3
    restart: unless-stopped
    networks:
      - cliente3_net

  cms-db-c3:
    image: mariadb:10.11
    container_name: cms-db-cliente3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass_cliente3
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress_pass_cliente3
    volumes:
      - cms_db_data_c3:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wordpress", "-pwordpress_pass_cliente3"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cliente3_net

  cms-app-c3:
    image: wordpress:latest
    container_name: cms-app-cliente3
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=cms-db-cliente3
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress_pass_cliente3
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - cms_app_data_c3:/var/www/html
    depends_on:
      cms-db-c3:
        condition: service_healthy
    networks:
      - cliente3_net

volumes:
  cms_db_data_c3:
  cms_app_data_c3:

networks:
  isp_net:
    external: true
  cliente3_net:
    driver: bridge