upstream portal_backend {
    server site-ISP:80;
}

upstream nextcloud_backend {
    server webmailISP:80;
}

# ==================================================
# Portal Principal
# ==================================================

server {

    listen 80;

    server_name nexustech.com.br www.nexustech.com.br;

    access_log /var/log/nginx/main.access.log;
    error_log /var/log/nginx/main.error.log;

    location / {

        proxy_pass http://portal_backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {

        root /usr/share/nginx/html;

    }

}

# ==================================================
# WEBMAIL / NEXTCLOUD
# ==================================================

server {

    listen 80;

    server_name webmail.nexustech.com.br;

    client_max_body_size 10G;

    proxy_read_timeout 3600;
    proxy_connect_timeout 3600;
    proxy_send_timeout 3600;

    location / {

        proxy_pass http://nextcloud_backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_request_buffering off;

    }

}