zone "nexustech.com.br" {
    type master;
    file "/etc/powerdns/zones/nexustech.conf";
};

zone "salesfilho.com.br" {
    type master;
    file "/etc/powerdns/clientes/cliente1/salesfilho.conf";
};

zone "cliente2.com.br" {
    type master;
    file "/etc/powerdns/clientes/cliente2/cliente2.conf";
};

zone "cliente3.com.br" {
    type master;
    file "/etc/powerdns/clientes/cliente3/cliente3.conf";
};