$TTL 86400

@ IN SOA ns.nexustech.com.br. root.nexustech.com.br. (
    2026061501
    3600
    1209600
    86400
)

@ IN NS ns.nexustech.com.br.

ns      IN A 192.168.0.10
site    IN A 192.168.0.30
mail    IN A 192.168.0.40
webmail IN A 192.168.0.50

www     IN CNAME site
imap    IN CNAME mail
pop     IN CNAME mail
smtp    IN CNAME mail

@       IN MX 10 mail.nexustech.com.br.
