$TTL 86400

@ IN SOA ns.nexustech.com.br. root.nexustech.com.br. (
    2026061502
    3600
    1800
    1209600
    86400
)

@ IN NS ns.nexustech.com.br.

ns      IN A 192.168.0.14

@       IN A 192.168.0.14
site    IN A 192.168.0.14
mail    IN A 192.168.0.14
webmail IN A 192.168.0.14

www     IN CNAME site
imap    IN CNAME mail
pop     IN CNAME mail
smtp    IN CNAME mail

@       IN MX 10 mail.nexustech.com.br.
