$TTL 86400

@ IN SOA ns.nexustech.com.br. root.nexustech.com.br. (
    2026062201
    3600
    1800
    1209600
    86400
)

@ IN NS ns.nexustech.com.br.

;DNS Server
ns      IN A 10.25.3.45

@       IN A 10.25.3.45
site    IN A 10.25.3.45

; Mail Server
mail    IN A 10.25.3.45
webmail IN A 10.25.3.45

; Aliases
www     IN CNAME site
imap    IN CNAME mail
pop     IN CNAME mail
smtp    IN CNAME mail

;MX Record
@       IN MX 10 mail.nexustech.com.br.
;SPF
@ IN TXT "v=spf1 mx -all"