# Mail location using Maildir per-user
mail_location = maildir:~/Maildir

# Do not force mail_uid/mail_gid unless you use a dedicated vmail user
# mail_uid = 1000
# mail_gid = 1000

namespace inbox {
  inbox = yes
}
