mail_driver = maildir
mail_home = /var/mail/vhosts/%{user | domain}/%{user | username}
mail_path = %{home}/Maildir
mail_inbox_path = %{home}/Maildir

namespace inbox {
  inbox = yes
}

mail_uid = 5000
mail_gid = 5000

mail_privileged_group = vmail

first_valid_uid = 5000
first_valid_gid = 5000