# Service definitions and sockets
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

service submission-login {
  inet_listener submission {
    port = 587
  }
}

service lmtp {
  unix_listener lmtp {
    mode = 0666
  }
}

service auth {
  # socket for dovecot-auth userdb (if used)
  unix_listener auth-userdb {
    mode = 0666
  }

  # socket for Postfix SASL
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }

  # allow auth process to run as dovecot user
  user = dovecot
}
