# Imagem base
FROM debian:stable-slim

# Instala PowerDNS e Nginx (proxy reverso)
RUN apt-get update && \
    apt-get install -y pdns-server pdns-backend-bind nginx && \
    rm -rf /var/lib/apt/lists/*

# Copia configurações
COPY pdns.conf /etc/powerdns/pdns.conf
COPY zones/ /etc/powerdns/zones/

# Copia conteúdo web
COPY web/ /var/www/html/

# Copia zonas DNS
COPY zones/ /etc/powerdns/zones/

# Exposição de portas
EXPOSE 53/tcp
EXPOSE 53/udp
EXPOSE 80/tcp

# Inicializa ambos os serviços
CMD ["pdns_server", "--daemon=no", "--guardian=no", "--loglevel=9"]
