FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y \
    netcat-openbsd \
    dnsutils \
    iputils-ping \
    telnet \
    bash \
    pdns-server \
    pdns-backend-bind && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY pdns.conf /etc/powerdns/pdns.conf

EXPOSE 53/tcp
EXPOSE 53/udp

CMD ["pdns_server","--daemon=no","--guardian=no"]